[package]
name = "flicker-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam.workspace = true
bytemuck.workspace = true
tracing.workspace = true
thiserror.workspace = true
flate2.workspace = true
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json = { workspace = true }
