[package]
name = "flicker-render"
version = "0.1.6"
edition.workspace = true
license.workspace = true

[dependencies]
flicker-core.workspace = true
wgpu.workspace = true
winit.workspace = true
glam.workspace = true
bytemuck.workspace = true
image.workspace = true
glyphon.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
pollster.workspace = true
