[package]
name = "flicker"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "2D game engine with networked persistent-world support"

[dependencies]
flicker-core.workspace = true
flicker-render.workspace = true
flicker-2d.workspace = true
flicker-script.workspace = true
flicker-net.workspace = true
flicker-app.workspace = true
flicker-scene.workspace = true
flicker-widgets.workspace = true
flicker-input-core.workspace = true
flicker-input-router.workspace = true
flicker-input-device.workspace = true
